scale: 1
metatile: 2
name: OSM Clear
description: A style designed for use with ClearTables
bounds: &world
  - -180
  - -85.05112877980659
  - 180
  - 85.05112877980659
center:
  - 0
  - 0
  - 4
format: "png"
interactivity: false
minzoom: 0
maxzoom: 19
srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"

# Various parts to be included later on
_parts:
  # Extents are used for tilemill, and don't actually make it to the generated XML
  extents: &extents
    extent: *world
    srs-name: "900913"
    srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
  extents84: &extents84
    extent: *world
    srs-name: "WGS84"
    srs: "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
  osm2pgsql: &osm2pgsql
    type: postgis
    dbname: "gis"
    key_field: ""
    geometry_field: "way"
    extent: "-20037508,-20037508,20037508,20037508"
Stylesheet:
  - style.mss
  - water.mss
  - transportation.mss
  - buildings.mss
  - aeroway.mss
Layer:
  - id: ocean-lz
    class: ocean water
    geometry: polygon
    <<: *extents
    Datasource:
      file: "data/simplified-water-polygons-complete-3857/simplified_water_polygons.shp"
      type: shape
    advanced: {}
    properties:
      maxzoom: 9
  - id: ocean
    class: ocean water
    geometry: polygon
    <<: *extents
    Datasource:
      file: "data/water-polygons-split-3857/water_polygons.shp"
      type: shape
    properties:
      minzoom: 10
    advanced: {}
  - id: water
    class: water
    geometry: polygon
    <<: *extents
    Datasource:
      <<: *osm2pgsql
      table: |-
        (SELECT
            way
          FROM water_areas
        ) AS water
  - id: waterways
    geometry: linestring
    <<: *extents
    Datasource:
      <<: *osm2pgsql
      table: |-
        (SELECT
            way,
            waterway,
            brunnel,
            intermittent
          FROM waterways
          ORDER BY layer
        ) AS waterways
    properties:
      minzoom: 6
  - id: buildings
    geometry: polygon
    <<: *extents
    Datasource:
      <<: *osm2pgsql
      table: |-
        (SELECT
            way,
            -- 3.66 is obtained by correlating the heights and level data in OSM
            -- raising to a power < 1 reduces the height range displayed which looks better
            least(greatest(3, COALESCE(height,levels*3.66,5)),400)^.7 AS render_height
          FROM buildings
          WHERE way_area > 0.01*!pixel_width!::real*!pixel_height!::real
          ORDER BY render_height, ST_YMin(way) DESC
        ) AS buildings
    properties:
      minzoom: 12
  - id: transportation-lz
    class: transportation
    geometry: linestring
    <<: *extents
    Datasource:
      <<: *osm2pgsql
      table: |-
        (SELECT
            way,
            class,
            layer,
            brunnel::text,
            z_order
          FROM roads
          WHERE class IN ('motorway','trunk','primary','secondary')
        UNION ALL
        SELECT
            way,
            class,
            layer,
            brunnel::text,
            z_order
          FROM rail
          WHERE class IN ('rail', 'subway')
          ORDER BY z_order
        ) AS transportation_lz
    properties:
      group-by: brunnel
      minzoom: 6
      maxzoom: 9
  - id: transportation-back-casing
    class: transportation
    geometry: linestring
    <<: *extents
    Datasource:
      <<: *osm2pgsql
      table: &transport_query |-
        (SELECT
            way,
            class,
            layer,
            brunnel::text -- does this need to be text?
          FROM (SELECT
              way,
              class,
              layer,
              brunnel,
              z_order,
              NULL::real AS way_area
            FROM roads
          UNION ALL
          SELECT
              way,
              class,
              layer,
              brunnel,
              z_order,
              NULL::real AS way_area
            FROM rail
          UNION ALL
          SELECT
              way,
              class,
              layer,
              brunnel,
              z_order,
              way_area
            FROM road_areas
            ORDER BY layer,
              z_order,
              way_area DESC NULLS LAST) AS q
        ) AS transportation
    properties:
      minzoom: 10
  - id: transportation
    class: transportation
    geometry: linestring
    <<: *extents
    Datasource:
      <<: *osm2pgsql
      table: *transport_query
    advanced: {}
    properties:
      group-by: layer
      minzoom: 10
  - id: aeroway
    geometry: linestring
    <<: *extents
    Datasource:
      <<: *osm2pgsql
      table: |-
        (SELECT
            way,
            aeroway
          FROM
            aeroway_line
        ) AS aeroway
    properties:
      minzoom: 12
