scale: 1
metatile: 2
name: "OSM Clear"
description: "A faithful reimplementation of the standard OpenStreetMap style"
bounds: &world
  - -180
  - -85.05112877980659
  - 180
  - 85.05112877980659
center:
  - 0
  - 0
  - 4
format: "png"
interactivity: false
minzoom: 0
maxzoom: 19
srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"

# Various parts to be included later on
_parts:
  # Extents are used for tilemill, and don't actually make it to the generated XML
  extents: &extents
    extent: *world
    srs-name: "900913"
    srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
  extents84: &extents84
    extent: *world
    srs-name: "WGS84"
    srs: "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
  osm2pgsql: &osm2pgsql
    type: "postgis"
    dbname: "gis"
    key_field: ""
    geometry_field: "way"
    extent: "-20037508,-20037508,20037508,20037508"

Stylesheet:
  - "style.mss"
  - "water.mss"
  - "transportation.mss"
Layer:
  - id: ocean-lz
    class: ocean water
    geometry: polygon
    <<: *extents
    Datasource:
      file: "data/simplified-water-polygons-complete-3857/simplified_water_polygons.shp"
      type: "shape"
    advanced: {}
    properties:
      maxzoom: 9
  - id: ocean
    class: ocean water
    geometry: polygon
    <<: *extents
    Datasource:
      file: "data/water-polygons-split-3857/water_polygons.shp"
      type: "shape"
    properties:
      minzoom: 10
    advanced: {}
  - id: water
    class: water
    geometry: polygon
    <<: *extents
    Datasource:
      <<: *osm2pgsql
      table: |-
        (SELECT
            way
          FROM water_areas
        ) AS water
  - id: transportation-lz
    geometry: linestring
    <<: *extents
    Datasource:
      <<: *osm2pgsql
      table: |-
        (SELECT
            way,
            class,
            layer,
            brunnel::text
          FROM roads
          WHERE class IN ('motorway','trunk','primary','secondary')
          ORDER BY z_order
        ) AS transportation_lz
    properties:
      group-by: brunnel
      minzoom: 6
      maxzoom: 9
  - id: transportation-back-casing
    geometry: linestring
    <<: *extents
    Datasource:
      <<: *osm2pgsql
      table: &roads_query |-
        (SELECT
            way,
            class,
            layer,
            brunnel::text
          FROM roads
          ORDER BY layer,
          -- CASE brunnel WHEN 'tunnel' THEN -1 WHEN 'bridge' THEN 1 ELSE 0 END,
          z_order
        ) AS transportation
    properties:
      minzoom: 10
  - id: "transportation"
    geometry: linestring
    <<: *extents
    Datasource:
      <<: *osm2pgsql
      table: *roads_query
    advanced: {}
    properties:
      group-by: layer
      minzoom: 10
