_prefs:
  mapid: ''
  saveCenter: false
_properties:
  transportation:
    "group-by": layer
scale: 1
metatile: 1
interactivity_layer: ''
name: OSM Clear
description: A style designed for use with ClearTables
bounds: &world
  - -180
  - -85.05112877980659
  - 180
  - 85.05112877980659
center:
  - 0
  - 0
  - 4
format: "png"
minzoom: 0
maxzoom: 19
srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
source: "tmsource:///path/to/osm-clear.tm2source"
styles:
  - style.mss
  - water.mss
  - transportation.mss
  - buildings.mss
  - aeroway.mss
  - place.mss
layers:
  - ocean-lz
  - ocean
  - water
  - waterways
  - buildings
  - transportation
  - aeroway
  - place
  - roads-text
